# Generated by Django 5.0.7 on 2024-08-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vatPercentage', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
