# Generated by Django 5.0.7 on 2024-08-23 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('vat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='vatPayment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vat.vat'),
        ),
    ]
