# Generated by Django 5.0.7 on 2024-08-23 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_vatpayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='vatPayment',
            new_name='vatPercentage',
        ),
    ]
